name: 🧪 E2E product sync build->   
on:
  workflow_dispatch:
    inputs:

      test_feature_branch_version:
        description: "Particular merge request db name."
        required: false
        #default: "test-alza-service"
        type: string

      randomizer_active:
        description: "Products variants randomizer engaging"
        required: false
        type: boolean

      products_amount:
        description: "number of simulated product variants"
        required: false
        type: string   
         
      test_case:
        description: "test cases"
        required: false
        type: choice
        #default: "alza"
        options:
          - alza
          - kaufland

  push:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
    

      - name: Status check and cache update
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "inputs ${{ toJSON(inputs) }}"
          echo "event name: ${{github.event_name}}"
          echo "CYPRESS_FEATURE_BRANCH_VERSION=${{ toJSON(github.event.inputs.test_feature_branch_version )}}" >> $GITHUB_ENV
          echo "CYPRESS_RANDOMIZER_ACTIVE=${{ toJSON(github.event.inputs.randomizer_active) }}" >> $GITHUB_ENV
          echo "CYPRESS_PRODUCTS_AMOUNT=${{ toJSON(github.event.inputs.products_amount)}}" >> $GITHUB_ENV
             
      - name: Checkout
        uses: actions/checkout@v3

      - name: dotenv-action (process.env access)
        id: dotenv
        uses: falti/dotenv-action@v1.0.2

      - name: Caches
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Cypress
            build
            node_modules
          key: ${{ runner.os }}-node_modules-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-build-

      - name: Set environment variables
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: |
          echo "E2E_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
          cat .env
          echo "CYPRESS_TEST_CASE=${{ steps.dotenv.outputs.CYPRESS_TEST_CASE }}" >> $GITHUB_ENV
          echo "CYPRESS_FEATURE_BRANCH_VERSION=${{ steps.dotenv.outputs.CYPRESS_FEATURE_BRANCH_VERSION }}" >> $GITHUB_ENV

      - name: Setting environment to ALZA
        if: ${{ github.event.inputs.test_case == 'alza' }}
        run: |
          echo "event name: ${{github.event_name}}"
          echo "E2E_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
          echo "CYPRESS_TEST_CASE=alza" >> $GITHUB_ENV

      - name: Setting environment to KAUFLAND
        if: ${{ github.event.inputs.test_case == 'kaufland' }}
        run: |
          echo "E2E_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
          echo "CYPRESS_TEST_CASE=kaufland" >> $GITHUB_ENV

      - name: Setting environment to SHOPTET
        if: ${{ github.event.inputs.test_case == 'shoptet' }}
        run: |
          echo "E2E_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
          echo "CYPRESS_TEST_CASE=shoptet" >> $GITHUB_ENV 

      - name: Install root dependencies
        uses: bahmutov/npm-install@v1

      - name: Cypress run (manual trigger .env source)
        if: ${{ (github.event.inputs.test_case == '') || (github.event_name == 'push') }}
        uses: cypress-io/github-action@v4
        id: cypress-e2e-manual
        with:
          env: true
          install: false
          browser: electron
          headed: false
          spec: cypress/e2e/api-call-round-${{env.CYPRESS_TEST_CASE}}.cy.js
        env:  
          CYPRESS_TEST_CASE: ${{env.CYPRESS_TEST_CASE}}
          CYPRESS_FEATURE_BRANCH_VERSION: ${{env.CYPRESS_FEATURE_BRANCH_VERSION}}

      - name: Cypress run alza (dispatch trigger)
        if: ${{ github.event.inputs.test_case == 'alza' }}
        uses: cypress-io/github-action@v4
        id: cypress-alza
        with:
          install: false
          #config: video=false, screenshotOnRunFailure=false
          browser: electron
          headed: false
          spec: cypress/e2e/api-call-round-alza.cy.js
        env: 
          CYPRESS_TEST_CASE: ${{env.CYPRESS_TEST_CASE}}
          CYPRESS_FEATURE_BRANCH_VERSION: ${{env.CYPRESS_FEATURE_BRANCH_VERSION}}

      - name: Cypress run kauflalnd (dispatch trigger)
        if: ${{ github.event.inputs.test_case == 'kaufland' }}
        uses: cypress-io/github-action@v4
        id: cypress-kaufland
        with:
          install: false
          # config: video=false,screenshotOnRunFailure=false
          browser: electron
          headed: false
          spec: cypress/e2e/api-call-round-kaufland.cy.js
       # env: 
         # CYPRESS_TEST_CASE: ${{env.CYPRESS_TEST_CASE}}
         # CYPRESS_FEATURE_BRANCH_VERSION: ${{env.CYPRESS_FEATURE_BRANCH_VERSION}}
  
