name: cypress-api
on: 
  workflow_dispatch:
  push:
jobs:
  cypress-run:
    runs-on: ubuntu-latest
  #  container: cypress/browsers:node16.13.2-chrome100-ff98
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Cypress.io
        uses: cypress-io/github-action@v4
        with:
          config: video=false

